import { firestore } from './api/firebase';
import { collection, getDocs } from 'firebase/firestore';
import Head from 'next/head'
import Card from '../components/card';

export default function Home( props: any ) {
	const { posts } = props;

	return (
		<div>
			<Head>
				<title>Next Blog</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className='max-w-sm mx-auto mt-5'>
				{
					posts.map((p: { main_image: string; id: string; title: string; excerpt: string }) =>
						<Card key={p.id} title={p.title} excerpt={p.excerpt} imgUrl={p.main_image} /> 
					)
				}
			</main>
		</div>
	)
}

export async function getServerSideProps() {
	const posts = collection(firestore, "posts");
	const querySnapshot = await getDocs(posts);

	const results: any[] = [];
	querySnapshot.forEach( snapshot => {
		results.push( { ...snapshot.data(), id: snapshot.id } )
	} )

	return {
		props : { posts: JSON.parse(JSON.stringify( results ))}
	}
}
